# -*- coding: utf-8 -*-
"""pdf_reader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b8EcgSA5N0WqhrL7Yuc_ilnQmt89FcNx
"""

!pip install vaderSentiment
!pip install textract

from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.tokenize import RegexpTokenizer
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

import textract
import re

!pip install PyMuPDF

import fitz

# pdf_document = 'DMPL AR2018.pdf'
pdf_document = 'AR_2017.pdf'
key_words = ['profit', 'Profit', 'income', 'Income', 'revenue', 'Revenue']


doc = fitz.open(pdf_document)

matchedPageArray = []
tmp_full_text=''

for current_page in range(len(doc)):
  page = doc.loadPage(current_page)

  for word in key_words:
    if page.searchFor(word):
      tmp_full_text =  tmp_full_text + '\n' + page.getText('text').replace('ﬂ ', 'fl').replace('ff ', 'ff').replace('ﬁ ', 'fi')
      matchedPageArray.append(current_page)

matchedPageArray = list(set(matchedPageArray))

print(matchedPageArray)

with open(f"full_text_key_info{pdf_document}.txt", "w") as text_file:
    text_file.write(tmp_full_text)

"""Start XLNet exploration

https://github.com/zihangdai/xlnet/blob/master/notebooks/colab_imdb_gpu.ipynb

https://github.com/zihangdai/xlnet
"""

! pip install sentencepiece

! wget https://storage.googleapis.com/xlnet/released_models/cased_L-24_H-1024_A-16.zip
! unzip cased_L-24_H-1024_A-16.zip